import "server-only";
import crypto from "node:crypto";
import { ApiError } from "@/lib/security/api";
import { validateTwilioWebhookSignature,getTwilioWebhookUrl } from "@/lib/communications/twilio";
import { createServiceSupabaseClient } from "@/lib/supabase/server";
import { persistSafetyClassification } from "@/lib/workflows/safety-persistence";
import { enqueueAlma } from "@/lib/workflows/alma";

const terminal=new Set(["completed","busy","failed","no-answer","canceled"]);
const rank:Record<string,number>={queued:1,initiated:2,ringing:3,answered:4,"in-progress":4,completed:8,busy:8,failed:8,"no-answer":8,canceled:8};
function iso(value:string|undefined){if(!value)return null;const time=Date.parse(value);return Number.isFinite(time)?new Date(time).toISOString():null}
function safePhone(value:string|undefined){return value&&/^\+[1-9]\d{7,14}$/.test(value)?value:null}
export function twilioEventKey(params:Record<string,string>,eventType:string){return crypto.createHash("sha256").update([params.CallSid,eventType,params.CallStatus,params.RecordingSid,params.TranscriptionSid,params.Timestamp].join("|")).digest("hex")}
export function verifyTwilioVoiceRequest(req:Request,params:Record<string,string>,path:string){const token=process.env.TWILIO_AUTH_TOKEN;if(!token)throw new ApiError("missing_configuration","Twilio voice authentication is not configured.");if(!validateTwilioWebhookSignature({authToken:token,signature:req.headers.get("x-twilio-signature")||"",url:getTwilioWebhookUrl(path),params}))throw new ApiError("unauthorized","Invalid Twilio signature.")}
export async function ingestTwilioVoice(params:Record<string,string>,eventType:string){const sid=params.CallSid;if(!/^CA[a-zA-Z0-9]{20,}$/.test(sid||""))throw new ApiError("bad_request","A valid Twilio CallSid is required.");const db=createServiceSupabaseClient(),eventKey=twilioEventKey(params,eventType);const event=await db.from("voice_provider_events").upsert({provider:"twilio",provider_call_id:sid,event_type:eventType,event_key:eventKey,payload_safe:{status:params.CallStatus||null,direction:params.Direction||null,errorCode:params.ErrorCode||null,recordingSid:params.RecordingSid||null,transcriptionStatus:params.TranscriptionStatus||null},occurred_at:iso(params.Timestamp)},{onConflict:"provider,event_key",ignoreDuplicates:true}).select("id").maybeSingle();if(!event.data)return{duplicate:true,callSid:sid};
  const from=safePhone(params.From),to=safePhone(params.To),direction=params.Direction||"unknown";const caller=direction.startsWith("inbound")?from:to;let contactId:null|string=null;if(caller){const{data:contact}=await db.from("contacts").upsert({phone:caller,full_name:params.CallerName||null,updated_at:new Date().toISOString()},{onConflict:"phone"}).select("id").single();contactId=contact?.id||null}
  const existingResult=await db.from("maintenance_tickets").select("id,call_status,call_started_at,call_ended_at,transcript,secondary_provider_ids").or(`twilio_call_sid.eq.${sid},and(provider.eq.twilio,provider_conversation_id.eq.${sid})`).maybeSingle();let existing=existingResult.data;
  if(!existing){const exactEleven=await db.from("maintenance_tickets").select("id,call_status,call_started_at,call_ended_at,transcript,secondary_provider_ids").contains("provider_metadata",{twilio_call_sid:sid}).maybeSingle();existing=exactEleven.data;if(existing)await db.from("maintenance_tickets").update({twilio_call_sid:sid,secondary_provider_ids:{twilio:sid}}).eq("id",existing.id)}
  const incoming=params.CallStatus||existing?.call_status||"initiated",accept=!existing||!existing.call_status||(rank[incoming]||0)>=(rank[existing.call_status]||0);const started=iso(params.StartTime)||iso(params.Timestamp)||(incoming==="initiated"||incoming==="ringing"||incoming==="in-progress"?new Date().toISOString():existing?.call_started_at||null);const ended=iso(params.EndTime)||(terminal.has(incoming)?iso(params.Timestamp)||new Date().toISOString():existing?.call_ended_at||null);const duration=Number(params.CallDuration||params.Duration);const transcript=params.TranscriptionText?.slice(0,100_000)||existing?.transcript||null;
  const payload={source:"twilio_voice",provider:existing?undefined:"twilio",provider_conversation_id:existing?undefined:sid,twilio_call_sid:sid,secondary_provider_ids:{...((existing?.secondary_provider_ids||{})as Record<string,unknown>),twilio:sid},tenant_name:params.CallerName||"Caller",phone:caller,recipient_phone:direction.startsWith("inbound")?to:from,direction,property:"Unassigned",issue_category:"Phone Call",issue:transcript||`Twilio ${direction} call`,urgency:"Medium",status:"Needs Review",call_status:accept?incoming:existing?.call_status,call_started_at:started,call_ended_at:ended,call_duration_seconds:Number.isFinite(duration)?duration:null,recording_available:Boolean(params.RecordingSid)||undefined,recording_sid:params.RecordingSid||undefined,transcription_sid:params.TranscriptionSid||undefined,transcript,provider_error_code:params.ErrorCode||undefined,provider_error_message:params.ErrorMessage?.slice(0,500)||undefined,parent_call_sid:params.ParentCallSid||undefined,contact_id:contactId,provider_metadata:{twilio_account_sid:params.AccountSid||null,last_event:eventType}};
  let ticketId:string;if(existing){const{error}=await db.from("maintenance_tickets").update(payload).eq("id",existing.id);if(error)throw new ApiError("server_error","Unable to update Twilio call.");ticketId=existing.id}else{const{data,error}=await db.from("maintenance_tickets").insert(payload).select("id").single();if(error)throw new ApiError("server_error","Unable to create Twilio call.");ticketId=data.id}
  await persistSafetyClassification(ticketId,transcript||params.ErrorMessage||`Twilio ${direction} call ${incoming}`);if(["busy","failed","no-answer","canceled"].includes(incoming)){await db.from("crm_tasks").upsert({title:`Follow up ${incoming} call`,description:`Twilio call ${sid} requires human follow-up.`,priority:"urgent",ticket_id:ticketId,contact_id:contactId,idempotency_key:`twilio-follow-up:${sid}`},{onConflict:"idempotency_key",ignoreDuplicates:true});await enqueueAlma({jobType:"failed_call_follow_up",entityType:"maintenance_ticket",entityId:ticketId,payload:{action:"create_internal_task",text:`${incoming} call`},idempotencyKey:`alma-twilio-follow-up:${sid}`})}
  await db.from("operations_feed").insert({type:"voice_call",title:`Twilio call ${incoming}`,description:`${direction} call status updated.`,related_ticket_id:ticketId});return{duplicate:false,callSid:sid,ticketId,status:incoming}
}
