import "server-only";
import { ApiError } from "@/lib/security/api";
import { decryptSecret, encryptSecret } from "@/lib/security/encryption";
import { createServiceSupabaseClient } from "@/lib/supabase/server";
export type Provider="google"|"microsoft";
export type Connection={id:string;user_id:string;provider:Provider;encrypted_access_token:string|null;encrypted_refresh_token:string|null;access_token_expires_at:string|null;shared_with_staff?:boolean};
const now=()=>new Date().toISOString();
export async function refreshEmailToken(connection:Connection){
  if(connection.access_token_expires_at&&Date.parse(connection.access_token_expires_at)>Date.now()+60_000&&connection.encrypted_access_token)return decryptSecret(connection.encrypted_access_token);
  if(!connection.encrypted_refresh_token)throw new ApiError("provider_failure",`${connection.provider} authorization expired; reconnect the account.`);
  const google=connection.provider==="google";
  const params=new URLSearchParams({client_id:google?process.env.GOOGLE_CLIENT_ID||"":process.env.MICROSOFT_CLIENT_ID||"",client_secret:google?process.env.GOOGLE_CLIENT_SECRET||"":process.env.MICROSOFT_CLIENT_SECRET||"",refresh_token:decryptSecret(connection.encrypted_refresh_token),grant_type:"refresh_token"});
  if(!google)params.set("scope","openid email offline_access User.Read Mail.Read Mail.ReadWrite Mail.Send");
  const response=await fetch(google?"https://oauth2.googleapis.com/token":"https://login.microsoftonline.com/common/oauth2/v2.0/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:params,cache:"no-store"});
  const value=await response.json() as Record<string,unknown>;
  if(!response.ok||typeof value.access_token!=="string")throw new ApiError("provider_failure",`${connection.provider} permission refresh failed; reconnect the account.`);
  const update:Record<string,unknown>={encrypted_access_token:encryptSecret(value.access_token),access_token_expires_at:new Date(Date.now()+Number(value.expires_in||3600)*1000).toISOString(),status:"connected",last_error:null,updated_at:now()};
  if(typeof value.refresh_token==="string")update.encrypted_refresh_token=encryptSecret(value.refresh_token);
  await createServiceSupabaseClient().from("provider_connections").update(update).eq("id",connection.id);
  return value.access_token;
}
const refresh=refreshEmailToken;
export async function emailProviderJson(url:string,token:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});if(!response.ok){if(response.status===401||response.status===403)throw new ApiError("provider_failure","Email authorization was revoked or lacks permission; reconnect the account.");throw new ApiError("provider_failure",`Email provider request failed (${response.status}).`)}if(response.status===202||response.status===204)return{};return response.json() as Promise<Record<string,unknown>>;}
const json=emailProviderJson;
const header=(headers:unknown,name:string)=>Array.isArray(headers)?String((headers as Array<Record<string,unknown>>).find(h=>String(h.name).toLowerCase()===name.toLowerCase())?.value||""):"";
const decode=(value:unknown)=>{if(typeof value!=="string")return null;try{return Buffer.from(value.replace(/-/g,"+").replace(/_/g,"/"),"base64").toString("utf8")}catch{return null}};
async function storeGmail(connection:Connection,message:Record<string,unknown>){const db=createServiceSupabaseClient(),payload=(message.payload||{})as Record<string,unknown>,headers=payload.headers,threadId=String(message.threadId),messageId=String(message.id),subject=header(headers,"Subject"),sender=header(headers,"From"),recipients=header(headers,"To").split(",").filter(Boolean),labels=Array.isArray(message.labelIds)?message.labelIds:[];const parts=Array.isArray(payload.parts)?payload.parts as Array<Record<string,unknown>>:[];const body=decode((payload.body as Record<string,unknown>|undefined)?.data)||decode((parts.find(p=>p.mimeType==="text/plain")?.body as Record<string,unknown>|undefined)?.data);const attachments=parts.filter(p=>(p.body as Record<string,unknown>|undefined)?.attachmentId).map(p=>({filename:p.filename,mimeType:p.mimeType,size:(p.body as Record<string,unknown>).size,attachmentId:(p.body as Record<string,unknown>).attachmentId}));const sent=new Date(Number(message.internalDate||Date.now())).toISOString();const{data:thread,error}=await db.from("email_threads").upsert({connection_id:connection.id,provider:"google",provider_thread_id:threadId,subject,participants:[sender,...recipients],last_message_at:sent,updated_at:now()},{onConflict:"connection_id,provider_thread_id"}).select("id").single();if(error)throw new ApiError("server_error","Unable to store Gmail thread.");await db.from("email_messages").upsert({thread_id:thread.id,connection_id:connection.id,provider_message_id:messageId,internet_message_id:header(headers,"Message-ID"),direction:"inbound",sender:{value:sender},recipients,cc:header(headers,"Cc").split(",").filter(Boolean),subject,body_text:body,attachment_metadata:attachments,is_read:!labels.includes("UNREAD"),provider_sent_at:sent,status:"received"},{onConflict:"connection_id,provider_message_id"});return String(message.historyId||"");}
async function syncGoogle(connection:Connection,token:string){const db=createServiceSupabaseClient();const cp=await db.from("sync_checkpoints").select("checkpoint").eq("provider","google").eq("owner_id",connection.user_id).eq("stream",connection.id).maybeSingle();let pageToken:string|undefined,historyId=String((cp.data?.checkpoint as Record<string,unknown>|undefined)?.historyId||"");let imported=0;do{const url=new URL(historyId?"https://gmail.googleapis.com/gmail/v1/users/me/history":"https://gmail.googleapis.com/gmail/v1/users/me/messages");if(historyId){url.searchParams.set("startHistoryId",historyId);url.searchParams.set("historyTypes","messageAdded")}if(pageToken)url.searchParams.set("pageToken",pageToken);url.searchParams.set("maxResults","100");const list=await json(url.toString(),token);const refs=historyId?(Array.isArray(list.history)?(list.history as Array<Record<string,unknown>>).flatMap(h=>Array.isArray(h.messagesAdded)?(h.messagesAdded as Array<Record<string,unknown>>).map(x=>x.message as Record<string,unknown>):[]):[]):Array.isArray(list.messages)?list.messages as Array<Record<string,unknown>>:[];for(const ref of refs){const id=String(ref.id||"");if(!id)continue;const detail=await json(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=full`,token);const next=await storeGmail(connection,detail);if(next)historyId=next;imported++;}if(typeof list.historyId==="string")historyId=list.historyId;pageToken=typeof list.nextPageToken==="string"?list.nextPageToken:undefined;}while(pageToken);await db.from("sync_checkpoints").upsert({provider:"google",owner_id:connection.user_id,stream:connection.id,cursor:null,checkpoint:{historyId},last_success_at:now(),last_error:null,updated_at:now()},{onConflict:"provider,owner_id,stream"});return imported;}
async function syncMicrosoft(connection:Connection,token:string){const db=createServiceSupabaseClient();const cp=await db.from("sync_checkpoints").select("cursor").eq("provider","microsoft").eq("owner_id",connection.user_id).eq("stream",connection.id).maybeSingle();let url=cp.data?.cursor||"https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/delta?$top=100&$select=id,conversationId,internetMessageId,subject,from,toRecipients,ccRecipients,receivedDateTime,isRead,body,hasAttachments";let imported=0,delta="";while(url){const page=await json(url,token);for(const m of Array.isArray(page.value)?page.value as Array<Record<string,unknown>>:[]){const sent=String(m.receivedDateTime||now()),threadKey=String(m.conversationId||m.id);const{data:thread,error}=await db.from("email_threads").upsert({connection_id:connection.id,provider:"microsoft",provider_thread_id:threadKey,subject:m.subject,last_message_at:sent,updated_at:now()},{onConflict:"connection_id,provider_thread_id"}).select("id").single();if(error)throw new ApiError("server_error","Unable to store Outlook thread.");await db.from("email_messages").upsert({thread_id:thread.id,connection_id:connection.id,provider_message_id:m.id,internet_message_id:m.internetMessageId,direction:"inbound",sender:m.from,recipients:m.toRecipients||[],cc:m.ccRecipients||[],subject:m.subject,body_text:(m.body as Record<string,unknown>|undefined)?.content,attachment_metadata:m.hasAttachments?[{available:true}]:[],is_read:m.isRead===true,provider_sent_at:sent,status:"received"},{onConflict:"connection_id,provider_message_id"});imported++;}delta=typeof page["@odata.deltaLink"]==="string"?String(page["@odata.deltaLink"]):delta;url=typeof page["@odata.nextLink"]==="string"?String(page["@odata.nextLink"]):"";}await db.from("sync_checkpoints").upsert({provider:"microsoft",owner_id:connection.user_id,stream:connection.id,cursor:delta,last_success_at:now(),last_error:null,updated_at:now()},{onConflict:"provider,owner_id,stream"});return imported;}
export async function syncEmail(userId?:string,provider?:Provider){const db=createServiceSupabaseClient();let query=db.from("provider_connections").select("id,user_id,provider,encrypted_access_token,encrypted_refresh_token,access_token_expires_at,shared_with_staff").eq("status","connected");if(userId)query=query.or(`shared_with_staff.eq.true,user_id.eq.${userId}`);if(provider)query=query.eq("provider",provider);const{data,error}=await query;if(error)throw new ApiError("server_error","Unable to load email connections.");let imported=0;for(const c of(data||[])as Connection[]){try{const token=await refresh(c);imported+=c.provider==="google"?await syncGoogle(c,token):await syncMicrosoft(c,token);await db.from("provider_connections").update({last_sync_at:now(),last_success_at:now(),last_error:null}).eq("id",c.id);}catch(error){await db.from("provider_connections").update({last_sync_at:now(),last_error:error instanceof Error?error.message:"Provider sync failed",status:"needs_reconnect"}).eq("id",c.id);throw error;}}return{connections:data?.length||0,imported};}
export async function emailAction(userId:string,messageId:string,action:"read"|"unread"|"archive"|"send",body?:{to?:string[];subject?:string;body?:string}){const db=createServiceSupabaseClient();const{data:message}=await db.from("email_messages").select("provider_message_id,connection_id,provider_connections!inner(id,user_id,provider,encrypted_access_token,encrypted_refresh_token,access_token_expires_at)").eq("id",messageId).single();if(!message)throw new ApiError("not_found","Message not found.");const c=(message.provider_connections as unknown)as Connection;if(c.user_id!==userId)throw new ApiError("forbidden","Message access denied.");const token=await refresh(c);if(action==="send"){if(!body?.to?.length||!body.subject||!body.body)throw new ApiError("bad_request","Recipients, subject, and body are required.");if(c.provider==="google"){const raw=Buffer.from(`To: ${body.to.join(", ")}\r\nSubject: ${body.subject}\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${body.body}`).toString("base64url");await json("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",token,{method:"POST",body:JSON.stringify({raw})});}else await json("https://graph.microsoft.com/v1.0/me/sendMail",token,{method:"POST",body:JSON.stringify({message:{subject:body.subject,body:{contentType:"Text",content:body.body},toRecipients:body.to.map(address=>({emailAddress:{address}}))},saveToSentItems:true})});return{success:true};}if(c.provider==="google"){const remove=action==="read"?["UNREAD"]:action==="archive"?["INBOX"]:[];const add=action==="unread"?["UNREAD"]:[];await json(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${message.provider_message_id}/modify`,token,{method:"POST",body:JSON.stringify({addLabelIds:add,removeLabelIds:remove})});}else{if(action==="archive")await json(`https://graph.microsoft.com/v1.0/me/messages/${message.provider_message_id}/move`,token,{method:"POST",body:JSON.stringify({destinationId:"archive"})});else await json(`https://graph.microsoft.com/v1.0/me/messages/${message.provider_message_id}`,token,{method:"PATCH",body:JSON.stringify({isRead:action==="read"})});}await db.from("email_messages").update(action==="read"?{is_read:true}:action==="unread"?{is_read:false}:{status:"archived"}).eq("id",messageId);return{success:true};}
