"use client";

import AppShell from "@/app/components/AppShell";
import { useCallback, useEffect, useState } from "react";

type Provider = { provider: "elevenlabs" | "google" | "microsoft"; configured: boolean; authenticated: boolean; status: string; verificationStatus: string; lastTestedAt: string | null; accountEmail: string | null; lastSync: string | null; lastSuccess: string | null; lastError: string | null; importedCount: number | null; importedLastRun: number; webhookConfigured: boolean | null };
const label = (provider: string) => provider === "elevenlabs" ? "ElevenLabs" : provider === "google" ? "Gmail" : "Microsoft 365";
const formatDate = (value: string | null) => value ? new Date(value).toLocaleString() : "Never";

export default function IntegrationsPage() {
  const [providers, setProviders] = useState<Provider[]>([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(""), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/integrations", { cache: "no-store" }); const json = await response.json(); if (!response.ok) setError(json.error || "Unable to load integration health."); else setProviders(json.providers || []); setLoading(false); }, []);
  useEffect(() => { let active = true; (async () => { const response = await fetch("/api/integrations", { cache: "no-store" }); const json = await response.json(); if (!active) return; if (!response.ok) setError(json.error || "Unable to load integration health."); else setProviders(json.providers || []); setLoading(false); })(); return () => { active = false; }; }, []);
  async function test(provider: string) { setBusy(`${provider}:test`); setError(""); const response = await fetch("/api/integrations/smoke", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider }) }); const json = await response.json(); if (!response.ok) setError(json.error || `${label(provider)} test failed.`); else setNotice(`${label(provider)} verification: ${json.status.replaceAll("_", " ")}.`); await load(); setBusy(""); }
  async function sync(provider: string) { setBusy(`${provider}:sync`); setError(""); const response = await fetch(provider === "elevenlabs" ? "/api/elevenlabs/sync" : "/api/email", { method: "POST" }); const json = await response.json(); if (!response.ok) setError(json.error || `${label(provider)} synchronization failed.`); else setNotice(provider === "elevenlabs" ? `Imported ${json.imported} conversations.` : `Imported ${json.imported} messages.`); await load(); setBusy(""); }
  async function disconnect(provider: string) { if (!window.confirm(`Disconnect ${label(provider)} from LegacyOS?`)) return; setBusy(`${provider}:disconnect`); const response = await fetch(`/api/oauth/${provider}/disconnect`, { method: "POST" }); const json = await response.json(); if (!response.ok) setError(json.error || "Disconnect failed."); else setNotice(`${label(provider)} disconnected.`); await load(); setBusy(""); }
  return <AppShell>
    <section className="rounded-[28px] bg-[#07110c] p-7 text-white md:p-9"><p className="text-[10px] uppercase tracking-[.28em] text-emerald-300">Production controls</p><h1 className="mt-4 text-4xl font-semibold md:text-5xl">Integrations.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-zinc-400">Configuration, authenticated verification, and synchronization are reported separately. Environment variables alone never produce a connected state.</p></section>
    {(error || notice) && <div role="status" className={`mt-5 rounded-xl border p-4 text-sm ${error ? "border-red-200 bg-red-50 text-red-700" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{error || notice}</div>}
    {loading ? <State title="Loading provider state" detail="Reading OAuth, smoke-test, and synchronization records…"/> : <section className="mt-6 grid gap-5 xl:grid-cols-3">{providers.map(provider => <article key={provider.provider} className="flex min-h-[460px] flex-col rounded-[24px] border border-black/[.06] bg-white p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.2em] text-zinc-400">{provider.provider === "elevenlabs" ? "Voice system" : "Company mailbox"}</p><h2 className="mt-2 text-2xl font-semibold">{label(provider.provider)}</h2></div><Status value={provider.status}/></div>
      <div className="mt-6 space-y-4"><Row label="Configured" value={provider.configured ? "Yes" : "Missing credentials"}/><Row label="Authenticated" value={provider.authenticated ? "Verified" : provider.verificationStatus.replaceAll("_", " ")}/><Row label="Last tested" value={formatDate(provider.lastTestedAt)}/><Row label="Last sync" value={formatDate(provider.lastSync)}/><Row label="Last successful sync" value={formatDate(provider.lastSuccess)}/>{provider.accountEmail && <Row label="Company account" value={provider.accountEmail}/>} {provider.provider === "elevenlabs" && <><Row label="Imported conversations" value={String(provider.importedCount ?? 0)}/><Row label="Imported last run" value={String(provider.importedLastRun)}/><Row label="Webhook secret" value={provider.webhookConfigured ? "Configured; delivery not yet proven" : "Missing"}/></>}</div>
      {provider.lastError && <div className="mt-5 rounded-xl border border-red-100 bg-red-50 p-3 text-xs text-red-700">{provider.lastError}</div>}
      <ProviderState provider={provider}/>
      <div className="mt-auto flex flex-wrap gap-2 pt-6"><button disabled={!!busy || !provider.configured} onClick={() => test(provider.provider)} className="rounded-lg border px-3 py-2 text-xs disabled:opacity-40">{busy === `${provider.provider}:test` ? "Testing…" : "Test connection"}</button><button disabled={!!busy || !provider.configured || (provider.provider !== "elevenlabs" && provider.status !== "connected")} onClick={() => sync(provider.provider)} className="rounded-lg bg-black px-3 py-2 text-xs text-white disabled:opacity-40">{busy === `${provider.provider}:sync` ? "Syncing…" : "Sync now"}</button>{provider.provider !== "elevenlabs" && <a href={`/api/oauth/${provider.provider}/start`} className="rounded-lg border px-3 py-2 text-xs">{provider.status === "connected" ? "Reconnect" : "Connect"}</a>}{provider.provider !== "elevenlabs" && provider.status === "connected" && <button disabled={!!busy} onClick={() => disconnect(provider.provider)} className="rounded-lg border border-red-200 px-3 py-2 text-xs text-red-700">Disconnect</button>}</div>
    </article>)}</section>}
  </AppShell>;
}

function ProviderState({ provider }: { provider: Provider }) { if (!provider.configured) return <Hint tone="warning">Add the required server credentials, then redeploy before testing.</Hint>; if (provider.verificationStatus === "permission_denied") return <Hint tone="error">The provider rejected the current permissions. Reconnect or correct provider-side access.</Hint>; if (provider.verificationStatus === "provider_unavailable") return <Hint tone="error">The provider could not be reached during the last test. Retry when service is available.</Hint>; if (provider.status === "needs_reconnect") return <Hint tone="warning">Authorization was revoked or expired. Reconnect this mailbox.</Hint>; if (!provider.lastSync) return <Hint>{provider.provider === "elevenlabs" ? "Never synchronized. Test the connection, then import calls from ElevenLabs." : "Connected but never synchronized. Run Sync now to import the mailbox."}</Hint>; if (provider.provider === "elevenlabs") return <Hint>Webhook path: <code className="select-all">/api/elevenlabs</code>. Use it with the canonical app origin and enable transcription, audio, and initiation-failure events.</Hint>; return <Hint>OAuth is stored encrypted. Sync uses the provider checkpoint and will request reconnection if authorization is revoked.</Hint>; }
function Hint({ children, tone }: { children: React.ReactNode; tone?: "warning" | "error" }) { return <div className={`mt-5 rounded-xl border p-3 text-xs leading-5 ${tone === "error" ? "border-red-100 bg-red-50 text-red-700" : tone === "warning" ? "border-amber-100 bg-amber-50 text-amber-800" : "border-zinc-100 bg-zinc-50 text-zinc-600"}`}>{children}</div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4 border-b border-black/[.05] pb-3 text-xs"><span className="text-zinc-400">{label}</span><span className="max-w-[60%] break-words text-right text-zinc-700">{value}</span></div>; }
function Status({ value }: { value: string }) { const good = ["connected", "authenticated", "healthy"].includes(value); return <span className={`rounded-full px-2.5 py-1 text-[9px] uppercase tracking-wide ${good ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{value.replaceAll("_", " ")}</span>; }
function State({ title, detail }: { title: string; detail: string }) { return <div className="mt-5 rounded-2xl border border-black/[.06] bg-white p-7"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm text-zinc-500">{detail}</p></div>; }
