export type SafetyClassification="emergency"|"urgent"|"routine"|"spam"|"unknown";
export type Urgency="Low"|"Medium"|"High"|"Urgent"|"Emergency";
const VERSION="legacy-safety-2026-07-20";
const emergency:[RegExp,string][]=[
  [/\b(fire|smoke|flames?)\b/i,"fire or smoke"],[/\b(gas (?:leak|odor|smell)|smell(?:s)? gas|carbon monoxide)\b/i,"gas or carbon-monoxide danger"],
  [/\b(flood(?:ing)?|burst pipe|water.*electrical)\b/i,"active flooding"],[/\b(sparking|electrocut|live wire|electrical fire)\b/i,"electrical danger"],
  [/\b(unconscious|not breathing|medical emergency|suicid|weapon|threat(?:en)?)\b/i,"medical or personal safety danger"],
  [/(?:\b(lock(?:ed)? out).*\b(child|baby|elderly|disabled|vulnerable)\b|\b(child|baby|elderly|disabled|vulnerable)\b.*\b(lock(?:ed)? out))/i,"vulnerable occupant lockout"]];
export function classifySafety(input:string){const text=input.trim();for(const[rule,reason]of emergency)if(rule.test(text))return{classification:"emergency" as const,reason,confidence:1,policyVersion:VERSION,requiresHuman:true};if(/\b(no heat|no water|sewage|major leak|locked out)\b/i.test(text))return{classification:"urgent" as const,reason:"time-sensitive habitability issue",confidence:.9,policyVersion:VERSION,requiresHuman:false};if(/\b(spam|telemarket|sales pitch)\b/i.test(text))return{classification:"spam" as const,reason:"unsolicited commercial content",confidence:.85,policyVersion:VERSION,requiresHuman:false};if(text.length<8)return{classification:"unknown" as const,reason:"insufficient information",confidence:.2,policyVersion:VERSION,requiresHuman:true};return{classification:"routine" as const,reason:"no deterministic safety trigger",confidence:.8,policyVersion:VERSION,requiresHuman:false};}
export function normalizeUrgency(value:unknown,context=""):Urgency{const requested=typeof value==="string"?value.trim().toLowerCase():"";if(["emergency","critical","life safety"].includes(requested))return"Emergency";if(["urgent","very high","severe"].includes(requested))return"Urgent";if(["high","important"].includes(requested))return"High";if(["low","routine","minor"].includes(requested))return"Low";const safety=classifySafety(context);if(safety.classification==="emergency")return"Emergency";if(safety.classification==="urgent")return"Urgent";return"Medium";}
export function requiresHumanReview(input:{urgency:Urgency;text?:string|null}){const text=input.text||"",safety=classifySafety(text);return input.urgency==="Emergency"||input.urgency==="Urgent"||safety.requiresHuman||/\b(?:lawyer|attorney|lawsuit|legal action|police|insurance claim|fair housing)\b/i.test(text)||/\b(?:human|manager|supervisor|call me|speak to someone)\b/i.test(text);}
export function isConsequentialAction(action:string){return["dispatch","send","call","financial_commitment","lease_change","access_change","emergency_decision"].includes(action);}
