"use client";

import AppShell from "@/app/components/AppShell";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowUpRight, CheckCircle2, ChevronRight, CircleAlert, Clock3, Mail, PhoneCall, RefreshCw, ShieldCheck, Wrench } from "lucide-react";

type Call = { id: string; tenant_name: string; property: string | null; urgency: string; ai_summary: string | null; direction?: string | null; call_started_at?: string | null; created_at?: string };
type Email = { id: string; subject: string | null; urgency: string; status: string; alma_classification: string | null };
type Lead = { id: string; status: string; desired_property: string | null; unit_type: string | null; lead_temperature: "Hot" | "Warm" | "Cold"; lead_score: number; next_follow_up_at: string | null; email_threads: { id: string; subject: string | null; crm_contacts: { full_name: string; email: string | null; phone: string | null } | null } };
type Integration = { provider: string; status: string; account_email: string | null };
type Dashboard = {
  metrics: { callsToday: number; callsWeek: number; inboundCalls: number; outboundCalls: number; missedFailed: number; callFollowUps: number; openEmergencies: number; emailsAwaitingReply: number; draftsAwaitingApproval: number; overdueFollowUps: number; newLeasingLeads: number; hotLeasingLeads: number; warmLeasingLeads: number; leasingCallbacksDue: number };
  urgentCalls: Call[]; inboundCalls: Call[]; outboundCalls: Call[]; emailQueue: Email[]; leasingLeads: Lead[];
  callVolume: Array<{ date: string; label: string; value: number }>;
  urgencyDistribution: Array<{ label: string; value: number }>;
  operations: Array<{ id: string; title: string; description: string; created_at: string }>;
  integrations: Integration[]; sync: { lastEmailSync: string | null };
  worker: { running: number; deadLetter: number };
};

const formatTime = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "Not yet";

export default function DashboardPage() {
  const [data, setData] = useState<Dashboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [syncing, setSyncing] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setError(""); const response = await fetch("/api/dashboard", { cache: "no-store" }); const json = await response.json(); if (!response.ok) setError(json.error || "Unable to load operations."); else setData(json); setLoading(false); }, []);
  useEffect(() => {
    let active = true;
    (async () => {
      const response = await fetch("/api/dashboard", { cache: "no-store" });
      const json = await response.json();
      if (!active) return;
      if (!response.ok) setError(json.error || "Unable to load operations.");
      else setData(json);
      setLoading(false);
    })();
    return () => { active = false; };
  }, []);
  async function syncMail() { setSyncing(true); setError(""); const response = await fetch("/api/email", { method: "POST" }); const json = await response.json(); if (!response.ok) setError(json.error || "Microsoft 365 synchronization failed."); else await load(); setSyncing(false); }
  const microsoft = useMemo(() => data?.integrations.find((item) => item.provider === "microsoft"), [data]);
  const emailConnected = microsoft?.status === "connected";
  const attentionCount = (data?.metrics.openEmergencies || 0) + (data?.metrics.draftsAwaitingApproval || 0) + (data?.metrics.leasingCallbacksDue || 0) + (data?.metrics.overdueFollowUps || 0);
  const maxCallVolume = Math.max(1, ...(data?.callVolume.map((item) => item.value) || [1]));

  return <AppShell>
    <section className="liquid-card flex flex-wrap items-center justify-between gap-5 rounded-[22px] border border-white/90 bg-white/75 px-5 py-4 shadow-[0_16px_35px_rgba(25,42,32,.07)]"><div><div className="flex items-center gap-3"><h1 className="text-xl font-semibold tracking-tight">Operations overview</h1><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-800"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>Live workspace</span></div><p className="mt-1 text-sm text-zinc-500">Leads, calls, approvals, and operational follow-through.</p></div><div className="flex flex-wrap gap-2"><button onClick={syncMail} disabled={syncing} className="inline-flex h-10 items-center gap-2 rounded-xl bg-[#12643e] px-4 text-sm font-medium text-white disabled:opacity-50"><RefreshCw size={15} className={syncing ? "animate-spin" : ""}/>{syncing ? "Syncing…" : "Sync mail"}</button><Link href="/email" className="inline-flex h-10 items-center gap-2 rounded-xl border border-zinc-200 bg-white px-3.5 text-sm font-medium text-zinc-700 shadow-sm hover:bg-zinc-50"><Mail size={15}/>Leads</Link></div></section>
    {error && (
      <StatePanel tone="error" title="Operations data is unavailable" detail={error} action={<button onClick={() => void load()}>Retry</button>}/>
    )}
    {loading && <StatePanel title="Loading command center" detail="Reading live email, call, ticket, vendor, and approval records..."/>}
    {data && <>
      {data.metrics.callsWeek === 0 && data.urgentCalls.length === 0 && <StatePanel title="No calls have been imported" detail="Phone CRM will populate after the configured call provider imports real conversation history."/>}
      <section className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]">
        <article className="liquid-card rounded-[22px] border border-white/80 bg-white/75 p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-zinc-400">Call activity</p><h2 className="mt-2 text-lg font-semibold">Seven-day call volume</h2><p className="mt-1 text-sm text-zinc-500">Real provider conversations imported into LegacyOS.</p></div><Link href="/calls" className="text-xs font-medium text-emerald-700">Open calls</Link></div><VolumeChart data={data.callVolume} max={maxCallVolume}/></article>
        <article className="liquid-card grid grid-cols-2 gap-px overflow-hidden rounded-[22px] border border-white/80 bg-zinc-100 shadow-sm"><Metric label="Calls today" value={data.metrics.callsToday}/><Metric label="Hot leads" value={data.metrics.hotLeasingLeads} alert={data.metrics.hotLeasingLeads > 0}/><Metric label="Warm leads" value={data.metrics.warmLeasingLeads}/><Metric label="Needs attention" value={attentionCount} alert={attentionCount > 0}/></article>
      </section>
      <section className="mt-6 grid gap-4 lg:grid-cols-[1.3fr_.7fr]">
        <article className="liquid-card rounded-2xl border border-white/80 bg-white/75 p-5 shadow-sm"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[.2em] text-zinc-400">Connection status</p><h2 className="mt-2 text-lg font-semibold">Microsoft 365 leasing intake</h2></div><StatusPill good={emailConnected} label={emailConnected ? "Connected" : "Needs setup"}/></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><FlowStep done={emailConnected} label="Shared inbox" detail={emailConnected ? microsoft?.account_email || "Connected" : "Connect Microsoft 365"}/><FlowStep done={Boolean(data.sync.lastEmailSync)} label="Inbox sync" detail={formatTime(data.sync.lastEmailSync)}/><FlowStep done={data.worker.deadLetter === 0} label="Automation worker" detail={data.worker.deadLetter ? `${data.worker.deadLetter} item needs review` : data.worker.running ? "Processing work" : "Ready"}/></div>{!emailConnected && <Link href="/email" className="mt-5 inline-flex items-center gap-1 text-sm font-medium text-emerald-700">Connect the shared leasing inbox <ArrowUpRight size={15}/></Link>}</article>
        <article className="liquid-card rounded-2xl border border-white/80 bg-white/75 p-5 shadow-sm"><p className="text-[10px] uppercase tracking-[.2em] text-zinc-400">Today&apos;s protection</p><div className="mt-3 flex gap-3"><ShieldCheck className="mt-0.5 text-emerald-600" size={22}/><div><h2 className="font-semibold">Approval gates stay on</h2><p className="mt-1 text-sm leading-5 text-zinc-500">Legacy can sort, draft, and assign. Staff approves external email, vendor contact, and any high-risk action.</p></div></div></article>
      </section>
      <section className="mt-6 grid gap-5 xl:grid-cols-[1.18fr_.82fr]">
          <Queue title="Leads" eyebrow="Microsoft 365" action={<Link href="/email" className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700">View all <ChevronRight size={14}/></Link>} empty={emailConnected ? "No leasing leads have been detected yet. Legacy will add them here after the next inbox sync." : "Connect the shared Microsoft 365 leasing inbox to begin collecting real leads."}>{data.leasingLeads.map((lead) => <Link key={lead.id} href={`/email?thread=${lead.email_threads.id}`} className="group flex items-center justify-between gap-4 rounded-xl border border-black/[.06] p-4 hover:border-emerald-200 hover:bg-emerald-50/40"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate font-medium">{lead.email_threads.crm_contacts?.full_name || "Unknown prospect"}</p><Temperature value={lead.lead_temperature} score={lead.lead_score}/></div><p className="mt-1 truncate text-sm text-zinc-500">{lead.desired_property || "Property needs review"}{lead.unit_type ? ` · ${lead.unit_type}` : ""}</p><p className="mt-1 truncate text-xs text-zinc-400">{lead.email_threads.subject || "No subject"} · {lead.email_threads.crm_contacts?.email || "No email captured"}</p></div><div className="shrink-0 text-right"><p className="text-xs text-zinc-500">{lead.next_follow_up_at ? `Follow-up ${formatTime(lead.next_follow_up_at)}` : "Needs review"}</p><ChevronRight className="ml-auto mt-2 text-zinc-300 group-hover:text-emerald-700" size={17}/></div></Link>)}</Queue>
        <Queue title="Needs a decision" eyebrow="Staff approval" action={<Link href="/email" className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700">Review inbox <ChevronRight size={14}/></Link>} empty="Nothing is waiting for approval. Legacy will put reply drafts and high-risk actions here instead of silently sending them."><Decision icon={Mail} count={data.metrics.draftsAwaitingApproval} label="Email drafts awaiting approval" href="/email"/><Decision icon={PhoneCall} count={data.metrics.leasingCallbacksDue} label="Leasing callbacks due" href="/leasing"/><Decision icon={Wrench} count={data.metrics.openEmergencies} label="Maintenance emergencies" href="/maintenance" danger/></Queue>
      </section>
      <section className="mt-6 grid gap-5 xl:grid-cols-2">
        <CallLane title="Inbound transcripts" eyebrow="Calls received" count={data.metrics.inboundCalls} calls={data.inboundCalls} empty="No inbound calls have been imported yet. When the call provider is connected, real transcripts will appear here."/>
        <CallLane title="Outbound calls" eyebrow="Calls placed" count={data.metrics.outboundCalls} calls={data.outboundCalls} empty="No outbound calls have been recorded. Legacy will only show calls confirmed by the connected provider."/>
      </section>
      <section className="mt-6 grid gap-5 xl:grid-cols-2">
        <Queue title="What Legacy did" eyebrow="Activity timeline" action={<Link href="/operations" className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700">Full timeline <ChevronRight size={14}/></Link>} empty="No activity has been recorded yet. Actions will appear here after calls, emails, tickets, or vendor workflows run.">{data.operations.map((item) => <div key={item.id} className="flex gap-3 border-b border-black/[.06] py-3 last:border-0"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-emerald-500"/><div className="min-w-0"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{item.title}</p><time className="text-xs text-zinc-400">{formatTime(item.created_at)}</time></div><p className="mt-1 text-sm leading-5 text-zinc-500">{item.description}</p></div></div>)}</Queue>
        <Queue title="Active response queue" eyebrow="Calls and email" action={<Link href="/email" className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700">Open communications <ChevronRight size={14}/></Link>} empty="No emails or urgent calls are waiting. New activity will appear here automatically.">{[...data.emailQueue.map((email) => ({ kind: "email" as const, row: email })), ...data.urgentCalls.map((call) => ({ kind: "call" as const, row: call }))].slice(0, 6).map((item) => item.kind === "email" ? <Link key={`email-${item.row.id}`} href={`/email?thread=${item.row.id}`} className="block rounded-xl border border-black/[.06] p-4 hover:bg-zinc-50"><div className="flex items-center justify-between gap-3"><p className="truncate font-medium">{item.row.subject || "(No subject)"}</p><Badge value={item.row.urgency}/></div><p className="mt-2 text-xs text-zinc-500">Email · {item.row.alma_classification || "Needs classification"} · {item.row.status}</p></Link> : <Link key={`call-${item.row.id}`} href={`/calls?selected=${item.row.id}`} className="block rounded-xl border border-black/[.06] p-4 hover:bg-zinc-50"><div className="flex items-center justify-between gap-3"><p className="truncate font-medium">{item.row.tenant_name}</p><Badge value={item.row.urgency}/></div><p className="mt-2 line-clamp-2 text-xs text-zinc-500">Call · {item.row.ai_summary || item.row.property || "Needs staff review"}</p></Link>)}</Queue>
      </section>
    </>}
  </AppShell>;
}

function Metric({ label, value, alert = false }: { label: string; value: number; alert?: boolean }) { return <div className="bg-white p-5"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-zinc-400">{label}</p><p className={`mt-2 text-3xl font-semibold tabular-nums ${alert ? "text-amber-700" : "text-zinc-950"}`}>{value}</p></div>; }
function VolumeChart({ data, max }: { data: Dashboard["callVolume"]; max: number }) { return <><div className="mt-6 flex h-28 items-end gap-2">{data.map((item) => <div key={item.date} className="group flex min-w-0 flex-1 flex-col items-center gap-2"><span className="text-[10px] text-zinc-400">{item.value}</span><div className="w-full rounded-t-lg bg-emerald-500/80 transition group-hover:bg-emerald-600" style={{ height: `${Math.max(5, item.value / max * 78)}px` }}/><span className="text-[10px] text-zinc-400">{item.label}</span></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{data.length ? <span className="rounded-full bg-zinc-100 px-2.5 py-1 text-[10px] text-zinc-600">Updated from imported call records</span> : <span className="text-sm text-zinc-500">No provider calls have been imported.</span>}</div></>; }
function StatusPill({ good, label }: { good: boolean; label: string }) { return <span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] uppercase tracking-wide ${good ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{good ? <CheckCircle2 size={12}/> : <CircleAlert size={12}/>} {label}</span>; }
function FlowStep({ done, label, detail }: { done: boolean; label: string; detail: string }) { return <div className="rounded-xl bg-zinc-50 p-3"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${done ? "bg-emerald-500" : "bg-amber-500"}`}/><p className="text-xs font-medium">{label}</p></div><p className="mt-2 truncate text-xs text-zinc-500">{detail}</p></div>; }
function Queue({ title, eyebrow, action, empty, children }: { title: string; eyebrow: string; action?: React.ReactNode; empty: string; children: React.ReactNode }) { const items = Array.isArray(children) ? children.filter(Boolean) : children ? [children] : []; return <article className="rounded-2xl border border-black/[.06] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.2em] text-zinc-400">{eyebrow}</p><h2 className="mt-2 text-lg font-semibold">{title}</h2></div>{action}</div><div className="mt-5 space-y-3">{items.length ? children : <p className="rounded-xl bg-zinc-50 p-4 text-sm leading-5 text-zinc-500">{empty}</p>}</div></article>; }
function CallLane({ title, eyebrow, count, calls, empty }: { title: string; eyebrow: string; count: number; calls: Call[]; empty: string }) { return <article className="liquid-card rounded-2xl border border-white/80 bg-white/75 p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.2em] text-zinc-400">{eyebrow}</p><h2 className="mt-2 text-lg font-semibold">{title}</h2></div><span className="rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800">{count}</span></div><div className="mt-5 space-y-2">{calls.length ? calls.map(call => <Link key={call.id} href={`/calls?selected=${call.id}`} className="block rounded-xl border border-black/[.06] bg-white/80 p-3 hover:border-emerald-200 hover:bg-emerald-50/40"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium">{call.tenant_name || "Unknown caller"}</p><Badge value={call.urgency}/></div><p className="mt-1 line-clamp-2 text-xs leading-5 text-zinc-500">{call.ai_summary || call.property || "Transcript needs staff review"}</p><p className="mt-2 text-[10px] uppercase tracking-wide text-zinc-400">{formatTime(call.call_started_at || call.created_at || null)}</p></Link>) : <p className="rounded-xl bg-zinc-50/80 p-4 text-sm leading-5 text-zinc-500">{empty}</p>}</div><Link href="/calls" className="mt-4 inline-flex items-center gap-1 text-xs font-medium text-emerald-700">Open call transcripts <ChevronRight size={14}/></Link></article>; }
function Decision({ icon: Icon, count, label, href, danger = false }: { icon: typeof Mail; count: number; label: string; href: string; danger?: boolean }) { return <Link href={href} className="flex items-center justify-between rounded-xl border border-black/[.06] p-4 hover:bg-zinc-50"><span className="flex items-center gap-3"><span className={`rounded-lg p-2 ${danger ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}><Icon size={16}/></span><span className="text-sm font-medium">{label}</span></span><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${count ? danger ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700" : "bg-zinc-100 text-zinc-500"}`}>{count}</span></Link>; }
function Badge({ value }: { value: string }) { const urgent = value === "Emergency" || value === "Urgent" || value === "High"; return <span className={`shrink-0 rounded-full px-2 py-1 text-[9px] uppercase tracking-wide ${urgent ? "bg-amber-50 text-amber-800" : "bg-zinc-100 text-zinc-600"}`}>{value}</span>; }
function Temperature({ value, score }: { value: Lead["lead_temperature"]; score: number }) { const tone = value === "Hot" ? "bg-red-50 text-red-700" : value === "Warm" ? "bg-amber-50 text-amber-800" : "bg-sky-50 text-sky-800"; return <span className={`shrink-0 rounded-full px-2 py-1 text-[9px] font-medium uppercase tracking-wide ${tone}`}>{value} {score}</span>; }
function StatePanel({ title, detail, action, tone }: { title: string; detail: string; action?: React.ReactNode; tone?: "error" }) { return <div className={`mt-6 rounded-2xl border p-5 ${tone === "error" ? "border-red-200 bg-red-50" : "border-black/[.06] bg-white"}`} role="status"><div className="flex gap-3"><Clock3 className={tone === "error" ? "text-red-600" : "text-zinc-400"} size={19}/><div><p className="font-medium">{title}</p><p className="mt-1 text-sm text-zinc-500">{detail}</p>{action && <div className="mt-4 [&_button]:rounded-xl [&_button]:bg-black [&_button]:px-4 [&_button]:py-2 [&_button]:text-sm [&_button]:text-white">{action}</div>}</div></div></div>; }
