"use client";

import { useState } from "react";
import { getSupabaseBrowserClient } from "@/lib/supabase";

export default function ResetPasswordPage() {
  const [password, setPassword] = useState(""), [confirm, setConfirm] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function reset(event: React.FormEvent) { event.preventDefault(); setError(""); if (password.length < 12) { setError("Use at least 12 characters."); return; } if (password !== confirm) { setError("Passwords do not match."); return; } setBusy(true); const supabase = getSupabaseBrowserClient(); const { data: { session } } = await supabase.auth.getSession(); if (!session) { setError("This recovery link is invalid or expired. Request another link."); setBusy(false); return; } const { error: updateError } = await supabase.auth.updateUser({ password }); if (updateError) { setError(updateError.message); setBusy(false); return; } await fetch("/api/auth/logout", { method: "POST", cache: "no-store" }); window.location.replace("/login?password=updated"); }
  return <main className="grid min-h-screen place-items-center bg-[#f5f5f3] p-6"><form onSubmit={reset} className="w-full max-w-lg rounded-[30px] border border-black/[.06] bg-white p-8"><p className="text-[10px] uppercase tracking-[.24em] text-zinc-400">Account recovery</p><h1 className="mt-4 text-3xl font-semibold">Set a new password</h1><p className="mt-3 text-sm text-zinc-500">The recovery session is verified by Supabase before the password is changed.</p><label className="mt-7 block text-xs text-zinc-500">New password<input required minLength={12} type="password" autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><label className="mt-5 block text-xs text-zinc-500">Confirm password<input required minLength={12} type="password" autoComplete="new-password" value={confirm} onChange={event => setConfirm(event.target.value)} className="mt-2 h-12 w-full rounded-xl border px-4"/></label><button disabled={busy} className="mt-7 h-12 w-full rounded-xl bg-black text-sm text-white disabled:opacity-50">{busy ? "Updating…" : "Update password"}</button>{error && <p role="alert" className="mt-5 rounded-xl border border-red-100 bg-red-50 p-4 text-sm text-red-700">{error}</p>}</form></main>;
}
